apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Release.Name }}-services
  labels:
    {{- include "platform.labels.common" . | nindent 4 }}
value: 1000
globalDefault: false
preemptionPolicy: Never
