# defaultClassName: traefik

clusterDnsName: ""
ingressAuthHost: api.apolo.us
fallbackHost: default.jobs.apolo.us
fallbackIngress:
  annotations: {}

cors:
  originList: []
  originListRegex: []

federatedPrometheus:
  auth:
    # Should be kubernetes.io/basic-auth type with `username` and `password` keys
    existingSecret: ""

    username: ""
    password: ""
