apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-error-page
  labels: {{ include "platform.labels.common" . | nindent 4 }}
    service: traefik
spec:
  errors:
    status:
    - "500-599"
    query: /
    service:
      name: {{ .Release.Name }}-fallback
      port: https
