apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fallback
  labels: {{ include "platform.labels.common" . | nindent 4 }}
spec:
  type: ExternalName
  externalName: {{ required "fallbackHost is required" .Values.fallbackHost }}
  ports:
  - name: https
    port: 443
