apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-ingress-auth
  labels: {{ include "platform.labels.common" . | nindent 4 }}
    service: traefik
spec:
  forwardAuth:
    address: https://{{ .Values.ingressAuthHost }}/oauth/authorize
    trustForwardHeader: true
