{{- define "platform.argocd.applications.sparkOperator.values" -}}
replicas: 1
spark:
  jobNamespaces: null
{{- end }}

{{- if .Values.applications.sparkOperator.enabled }}
{{- $cfg := deepCopy .Values.applications.sparkOperator -}}
{{- $_ := set $cfg "root" . -}}
{{- $_ := set $cfg "defaultValues" (include "platform.argocd.applications.sparkOperator.values" . | fromYaml) -}}
{{- include "platform.argocd.application" $cfg }}
{{- end }}
