{{- if and .Values.applications.externalSecrets.enabled .Values.externalSecrets }}
{{- $syncWave := add 2 (int (required "applications.externalSecrets.syncWave is required" .Values.applications.externalSecrets.syncWave)) -}}
{{- range .Values.externalSecrets }}
{{- $externalSecret := deepCopy . -}}
{{- $_ := unset $externalSecret "secretStoreRef" -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.name | quote }}
  labels: {{ include "platform.labels.standard" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $syncWave | quote }}
spec:
  secretStoreRef:
    name: {{ $.Release.Name }}-vault-secret-store
    kind: ClusterSecretStore
  {{- toYaml $externalSecret | nindent 2 }}
{{- end }}
{{- end }}
