{{- range .Values.externalSecretObjects }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name | quote }}
  labels: {{ include "platform.labels.standard" $ | nindent 4 }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Release.Name }}-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .name | quote }}
    creationPolicy: "Owner"
    template:
      metadata:
        labels: {{ include "platform.labels.standard" $ | nindent 4 }}
  data:
    {{- range $key, $ref := .data }}
    - secretKey: {{ $key | quote }}
      remoteRef:
        key: {{ $ref.key | quote }}
        property: {{ $ref.property | quote }}
    {{- end }}
{{- end }}
