{{- if and .Values.applications.externalSecrets.enabled .Values.externalSecrets }}
{{- $syncWave := add 2 (int (required "applications.externalSecrets.syncWave is required" .Values.applications.externalSecrets.syncWave)) -}}
{{- range .Values.externalSecrets }}
{{- $externalSecret := deepCopy . -}}
{{- $_ := unset $externalSecret.spec "secretStoreRef" -}}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $externalSecret.metadata.name | quote }}
  labels:
    {{- include "platform.labels.standard" $ | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $syncWave | quote }}
spec:
  secretStoreRef:
    name: {{ $.Release.Name }}-vault-secret-store
    kind: ClusterSecretStore
  {{- if not $externalSecret.spec.refreshInterval }}
  refreshInterval: '15s'
  {{- end }}
  {{- toYaml $externalSecret.spec | nindent 2 }}
{{ end }}
{{- end }}
