{{- define "platform.argocd.applications.platformSecrets.values" -}}
{{- $platformUrls := include "platform.urls" . | fromYaml -}}
image:
  repository: ghcr.io/neuro-inc/platformsecrets
securityContext:
  enabled: true
platform:
  clusterName: {{ include "platform.clusterName" . }}
  authUrl: {{ get $platformUrls "authUrl" }}
  eventsUrl: {{ printf "%s/apis/events" (get $platformUrls "eventsUrl") }}
  token:
    {{- include "platform.token" . | nindent 4 }}
secretsNamespace: platform-jobs
ingress:
  enabled: true
  {{- with .Values.defaultIngressClassName }}
  ingressClassName: {{ . }}
  {{- end }}
  hosts:
  - {{ include "platform.clusterDnsName" . }}
service:
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: NEURO_SECRETS_SESSION
priorityClassName: {{ include "platform.priorityClassName" . }}
{{- with .Values.sentry }}
sentry:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}

{{- if .Values.argocdApplications.platformSecrets.enabled }}
{{- $cfg := deepCopy .Values.argocdApplications.platformSecrets -}}
{{- $_ := set $cfg "root" . -}}
{{- $_ := set $cfg "defaultValues" (include "platform.argocd.applications.platformSecrets.values" . | fromYaml) -}}
{{- include "platform.argocd.application" $cfg }}
{{- end }}
