{{- if .Values.argocdApplications.platformExternalSecrets.enabled }}
{{- $cfg := deepCopy .Values.argocdApplications.platformExternalSecrets -}}
{{- $_ := set $cfg "root" . -}}
{{- $_ := set $cfg "targetRevision" .Chart.Version -}}
{{- $_ := set $cfg "defaultValues" dict -}}
{{- include "platform.argocd.application" $cfg }}
{{- end }}
